# Generated by Django 4.1.5 on 2023-01-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230126_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
