# Generated by Django 4.1.5 on 2023-02-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('shop', '0005_vpnprofile_active_until_vpnprofile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_id', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('card_first_six', models.CharField(max_length=6)),
                ('card_last_four', models.CharField(max_length=4)),
                ('card_type', models.CharField(max_length=20)),
                ('card_exp_date', models.CharField(max_length=5)),
                ('subscription_id', models.CharField(max_length=512, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('payment_method', models.CharField(max_length=512, null=True)),
                ('is_test', models.BooleanField()),
                ('paid', models.BooleanField(default=False)),
                ('vpn_profile',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.vpnprofile')),
            ],
            options={
                'verbose_name': 'Replenishment',
                'verbose_name_plural': 'Replenishments',
            },
        ),
    ]
