# Generated by Django 3.2.9 on 2023-01-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230126_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnserver',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
