# Generated by Django 4.1.6 on 2023-02-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0005_vpnprofile_active_until_vpnprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnprofile',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
